require('dotenv').config();
const fs = require('node:fs');
const path = require('node:path');
const {
  Client, GatewayIntentBits, PermissionsBitField, ChannelType, REST, Routes,
  SlashCommandBuilder, EmbedBuilder, ActionRowBuilder, ButtonBuilder, ButtonStyle,
  ModalBuilder, TextInputBuilder, TextInputStyle
} = require('discord.js');

const { TOKEN, CLIENT_ID, GUILD_ID, STAFF_ROLE_IDS, LOG_CHANNEL_ID } = process.env;
if (!TOKEN || !CLIENT_ID || !GUILD_ID) throw new Error('Brak TOKEN, CLIENT_ID lub GUILD_ID w .env');

const client = new Client({ intents: [GatewayIntentBits.Guilds] });
const P = PermissionsBitField.Flags;
const staffIds = (STAFF_ROLE_IDS || '').split(',').map(x => x.trim()).filter(Boolean);
const DATA_DIR = path.join(process.cwd(), 'data');
const DATA_FILE = path.join(DATA_DIR, 'zw-complete.json');
const DEFAULT = { nextNumber: 1, personnel: {}, applications: {}, exams: {}, reports: [], meldunki: [], rozkazy: [], actions: [], trainings: [], trainingExams: [], qualifications: [], duty: {} };

function load(){ fs.mkdirSync(DATA_DIR,{recursive:true}); if(!fs.existsSync(DATA_FILE)) fs.writeFileSync(DATA_FILE,JSON.stringify(DEFAULT,null,2)); try { const d=JSON.parse(fs.readFileSync(DATA_FILE,'utf8')); return {...DEFAULT,...d,personnel:d.personnel||{},applications:d.applications||{},exams:d.exams||{},reports:d.reports||[],meldunki:d.meldunki||[],rozkazy:d.rozkazy||[],actions:d.actions||[],trainings:d.trainings||[],trainingExams:d.trainingExams||[],qualifications:d.qualifications||[],duty:d.duty||{}}; } catch { return structuredClone(DEFAULT); } }
let db=load();
function save(){fs.mkdirSync(DATA_DIR,{recursive:true});fs.writeFileSync(DATA_FILE,JSON.stringify(db,null,2));}
const norm=s=>String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]/g,'');
const aliases={
  contact:['kontakt'], panel:['panel-podania'], requirements:['wymagania-rekrutacji'], applications:['podania-wewnetrzne'], results:['wyniki-rekrutacji'], candidateExam:['egzamin-kandydata'], recruitmentStatus:['status-rekrutacji'],
  reports:['raporty','raporty-sluzbowe','raporty sluzbowe','raport'], meldunki:['meldunki','meldunki-sluzbowe','meldunek'], orders:['rozkazy','rozkaz'], promotions:['awanse','awans'], demotions:['degradacje','degradacja'], proceedings:['postepowania','postepowanie'], awards:['wyroznienia','wyroznienie'], archive:['archiwum-kadr','archiwum kadr'], materials:['materialy','materialy-szkoleniowe'], trainings:['szkolenia','szkolenie'], exams:['egzaminy','egzamin'], examResults:['wyniki-egzaminow','wyniki egzaminow','wyniki-egzaminow'], qualifications:['kwalifikacje','kwalifikacja'], command:['komenda-glowna','komenda glowna'], unit:['wydzial','wydzialy']
};
function findChannel(guild,key){const list=aliases[key]||[key]; const wanted=list.map(norm); return guild.channels.cache.find(c=>c.type===ChannelType.GuildText&&wanted.includes(norm(c.name)))||null;}
function findCategory(guild){return guild.channels.cache.find(c=>c.type===ChannelType.GuildCategory&&norm(c.name)==='rekrutacjakandydat')||null;}
function staff(m){return !!m&&(m.permissions.has(P.Administrator)||staffIds.some(id=>m.roles.cache.has(id)));}
function personnel(user){if(!db.personnel[user.id]){db.personnel[user.id]={userId:user.id,username:user.username,number:`ZW-${String(db.nextNumber++).padStart(4,'0')}`,rank:'Kandydat',points:0,reprimands:0,awards:[],history:[],qualifications:[],trainings:[],dutyMinutes:0,joinedAt:new Date().toISOString()};save();}return db.personnel[user.id];}
function action(type,target,actor,details){db.actions.push({type,target,actor,details,at:new Date().toISOString()});save();}
async function sendLog(guild,title,description){if(!LOG_CHANNEL_ID)return;const c=guild.channels.cache.get(LOG_CHANNEL_ID);if(c?.isTextBased())await c.send({embeds:[new EmbedBuilder().setTitle(title).setDescription(description).setTimestamp()] }).catch(()=>{});}
async function post(guild,key,embed){const c=findChannel(guild,key);if(!c)return null;return c.send({embeds:[embed]}).catch(()=>null);}
const ranks=['Kandydat','Szeregowy','Starszy szeregowy','Kapral','Plutonowy','Sierżant','Starszy sierżant','Chorąży','Podporucznik','Porucznik','Kapitan','Major','Podpułkownik','Pułkownik','Generał brygady','Generał dywizji','Generał broni'];
const rankChoices=ranks.map(x=>({name:x,value:x}));
const Q=[
['Jaki jest podstawowy cel Żandarmerii Wojskowej?',['Zapewnianie przestrzegania dyscypliny wojskowej','Prowadzenie sportu','Administracja cywilna','Kontrola lotnicza'],0],
['Gdzie ŻW może wykonywać zadania związane z ochroną porządku?',['Tylko poza jednostkami','Na terenach i obiektach wojskowych oraz w miejscach publicznych w zakresie prawa','Wyłącznie w koszarach','Tylko podczas wojny'],1],
['Jak wykonywać polecenia przełożonego w RP?',['Ignorować','Zgodnie z regulaminem i zasadami RP','Publikować','Przekazywać przypadkowym osobom'],1],
['Co oznacza RP?',['Real Play','RolePlay','Rapid Patrol','Regulamin Personalny'],1],
['Jak zachować się podczas kontroli RP?',['Prowokować','Kulturalnie, spokojnie i zgodnie z procedurą','Uciekać','Spamować'],1],
['Czy informacje kadrowe wolno przekazywać osobom nieuprawnionym?',['Tak','Nie','Zawsze','Tylko poza Discordem'],1],
['Jaki powinien być meldunek radiowy?',['Chaotyczny','Krótki, jasny i rzeczowy','Same emotikony','Bez informacji'],1],
['Co oznacza dyscyplina służbowa?',['Dowolność','Przestrzeganie poleceń, regulaminów i zasad służby','Tylko mundur','Brak odpowiedzialności'],1],
['Co zrobić, gdy sytuacja przekracza możliwości patrolu?',['Nic','Wezwać wsparcie i przekazać meldunek','Opuścić służbę','Usunąć dokumentację'],1],
['Jak kandydat powinien zachować się podczas egzaminu?',['Korzystać z podpowiedzi','Samodzielnie i uczciwie odpowiadać','Spamować','Ignorować egzaminatora'],1]
];
function cmd(name,desc){return new SlashCommandBuilder().setName(name).setDescription(desc);}
const commands=[
cmd('zw-panel','Publikuje panel rekrutacyjny w istniejącym kanale'),cmd('zw-zamknij','Zamyka aktualny ticket'),cmd('zw-podania','Pokazuje statystyki podań'),cmd('zw-egzaminy','Pokazuje statystyki egzaminów'),
cmd('zw-raport','Złóż raport służbowy'),cmd('zw-meldunek','Złóż meldunek służbowy'),
cmd('zw-rozkaz','Dodaj rozkaz').addStringOption(o=>o.setName('tytul').setDescription('Tytuł').setRequired(true)).addStringOption(o=>o.setName('tresc').setDescription('Treść').setRequired(true)),
cmd('zw-plus','Przyznaj plus').addUserOption(o=>o.setName('osoba').setDescription('Funkcjonariusz').setRequired(true)).addIntegerOption(o=>o.setName('punkty').setDescription('Punkty').setMinValue(1).setMaxValue(100).setRequired(true)).addStringOption(o=>o.setName('powod').setDescription('Powód').setRequired(true)),
cmd('zw-minus','Przyznaj minus').addUserOption(o=>o.setName('osoba').setDescription('Funkcjonariusz').setRequired(true)).addIntegerOption(o=>o.setName('punkty').setDescription('Punkty').setMinValue(1).setMaxValue(100).setRequired(true)).addStringOption(o=>o.setName('powod').setDescription('Powód').setRequired(true)),
cmd('zw-awans','Nadaj stopień').addUserOption(o=>o.setName('osoba').setDescription('Funkcjonariusz').setRequired(true)).addStringOption(o=>o.setName('stopien').setDescription('Stopień').setRequired(true).addChoices(...rankChoices)).addStringOption(o=>o.setName('powod').setDescription('Powód').setRequired(true)),
cmd('zw-degradacja','Zmień stopień w dół').addUserOption(o=>o.setName('osoba').setDescription('Funkcjonariusz').setRequired(true)).addStringOption(o=>o.setName('stopien').setDescription('Nowy stopień').setRequired(true).addChoices(...rankChoices)).addStringOption(o=>o.setName('powod').setDescription('Powód').setRequired(true)),
cmd('zw-wyroznienie','Dodaj wyróżnienie').addUserOption(o=>o.setName('osoba').setDescription('Funkcjonariusz').setRequired(true)).addStringOption(o=>o.setName('opis').setDescription('Opis').setRequired(true)),
cmd('zw-postepowanie','Dodaj postępowanie').addUserOption(o=>o.setName('osoba').setDescription('Funkcjonariusz').setRequired(true)).addStringOption(o=>o.setName('opis').setDescription('Opis').setRequired(true)),
cmd('zw-funkcjonariusz','Pokaż kartę funkcjonariusza').addUserOption(o=>o.setName('osoba').setDescription('Osoba')),
cmd('zw-szkolenie','Zapisz ukończone szkolenie').addUserOption(o=>o.setName('osoba').setDescription('Funkcjonariusz').setRequired(true)).addStringOption(o=>o.setName('nazwa').setDescription('Szkolenie').setRequired(true)).addStringOption(o=>o.setName('wynik').setDescription('Wynik').setRequired(true)),
cmd('zw-szkolenie-utworz','Opublikuj szkolenie').addStringOption(o=>o.setName('nazwa').setDescription('Nazwa').setRequired(true)).addStringOption(o=>o.setName('opis').setDescription('Opis').setRequired(true)),
cmd('zw-material','Dodaj materiał szkoleniowy').addStringOption(o=>o.setName('tytul').setDescription('Tytuł').setRequired(true)).addStringOption(o=>o.setName('tresc').setDescription('Treść').setRequired(true)),
cmd('zw-kwalifikacja','Dodaj kwalifikację').addUserOption(o=>o.setName('osoba').setDescription('Funkcjonariusz').setRequired(true)).addStringOption(o=>o.setName('nazwa').setDescription('Kwalifikacja').setRequired(true)).addStringOption(o=>o.setName('status').setDescription('Status').setRequired(true)),
cmd('zw-egzamin-szkolenie','Zapisz wynik egzaminu szkoleniowego').addUserOption(o=>o.setName('osoba').setDescription('Funkcjonariusz').setRequired(true)).addStringOption(o=>o.setName('nazwa').setDescription('Egzamin').setRequired(true)).addIntegerOption(o=>o.setName('procent').setDescription('Wynik %').setMinValue(0).setMaxValue(100).setRequired(true)),
cmd('zw-sluzba','Rozpocznij lub zakończ służbę').addStringOption(o=>o.setName('akcja').setDescription('Akcja').setRequired(true).addChoices({name:'rozpocznij',value:'start'},{name:'zakończ',value:'stop'})).addStringOption(o=>o.setName('notatka').setDescription('Notatka')),
cmd('zw-archiwum','Pokaż historię kadrową').addUserOption(o=>o.setName('osoba').setDescription('Funkcjonariusz').setRequired(true)),cmd('zw-statystyki','Pokaż statystyki systemu ŻW')
].map(x=>x.toJSON());

function panel(){return {embeds:[new EmbedBuilder().setTitle('🇵🇱 ŻANDARMERIA WOJSKOWA — REKRUTACJA').setDescription('🎓 **ZŁÓŻ PODANIE** — prywatny ticket z formularzem.\n\n📝 **EGZAMIN** — prywatny ticket z automatycznym egzaminem.\n\n🔒 Ticket widzi kandydat i uprawniona kadra.')],components:[new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('new_app').setLabel('Złóż podanie').setEmoji('🎓').setStyle(ButtonStyle.Primary),new ButtonBuilder().setCustomId('new_exam').setLabel('Egzamin').setEmoji('📝').setStyle(ButtonStyle.Success))]};}
async function ticket(i,type){const cat=findCategory(i.guild);if(!cat)return i.reply({content:'❌ Brak istniejącej kategorii REKRUTACJA — KANDYDAT. Nie tworzę kategorii.',ephemeral:true});const topic=`ZW-TICKET:${type}:${i.user.id}`;const old=i.guild.channels.cache.find(c=>c.type===ChannelType.GuildText&&c.topic===topic);if(old)return i.reply({content:`❌ Masz już ticket: ${old}`,ephemeral:true});const ow=[{id:i.guild.roles.everyone.id,deny:[P.ViewChannel]},{id:i.user.id,allow:[P.ViewChannel,P.SendMessages,P.ReadMessageHistory]}];staffIds.forEach(id=>ow.push({id,allow:[P.ViewChannel,P.SendMessages,P.ReadMessageHistory,P.ManageMessages]}));if(i.guild.members.me)ow.push({id:i.guild.members.me.id,allow:[P.ViewChannel,P.SendMessages,P.ReadMessageHistory,P.ManageChannels,P.ManageMessages]});const safe=i.user.username.toLowerCase().replace(/[^a-z0-9-]/g,'-').slice(0,35)||'kandydat';const ch=await i.guild.channels.create({name:`${type==='exam'?'egzamin':'podanie'}-${safe}`,type:ChannelType.GuildText,parent:cat.id,topic,permissionOverwrites:ow});await i.reply({content:`✅ Ticket utworzony: ${ch}`,ephemeral:true});
if(type==='application'){const m=new ModalBuilder().setCustomId(`app:${ch.id}`).setTitle('Podanie do Żandarmerii Wojskowej');[['wiek','Wiek',TextInputStyle.Short],['dane','Imię i nazwisko RP',TextInputStyle.Short],['exp','Doświadczenie',TextInputStyle.Paragraph],['mot','Motywacja',TextInputStyle.Paragraph],['czas','Dyspozycyjność',TextInputStyle.Paragraph]].forEach(([id,label,style])=>m.addComponents(new ActionRowBuilder().addComponents(new TextInputBuilder().setCustomId(id).setLabel(label).setStyle(style).setRequired(true).setMaxLength(1000))));return i.followUp({content:'📋 Wypełnij formularz podania.',ephemeral:true}).then(()=>i.showModal(m)).catch(()=>{});}
await ch.send({content:`<@${i.user.id}>`,embeds:[new EmbedBuilder().setTitle('📝 EGZAMIN ŻW').setDescription('10 pytań • minimum 70% • wynik zapisuje się automatycznie.')],components:[new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('exam_start').setLabel('Rozpocznij egzamin').setStyle(ButtonStyle.Success),new ButtonBuilder().setCustomId('close').setLabel('Zamknij ticket').setStyle(ButtonStyle.Danger))]});}
async function question(ch,uid,n){const q=Q[n];const row=new ActionRowBuilder();q[1].forEach((a,k)=>row.addComponents(new ButtonBuilder().setCustomId(`ans:${k}`).setLabel(`${String.fromCharCode(65+k)}. ${a}`.slice(0,80)).setStyle(ButtonStyle.Secondary)));await ch.send({content:`<@${uid}>`,embeds:[new EmbedBuilder().setTitle(`📝 EGZAMIN ŻW • ${n+1}/${Q.length}`).setDescription(q[0])],components:[row]});}
async function startExam(i){db.exams[i.user.id]={userId:i.user.id,channelId:i.channel.id,question:0,score:0,status:'W_TRAKCIE',startedAt:new Date().toISOString()};save();await question(i.channel,i.user.id,0);return i.reply({content:'✅ Egzamin rozpoczęty.',ephemeral:true});}
async function answer(i,k){const e=db.exams[i.user.id];if(!e||e.channelId!==i.channel.id||e.status!=='W_TRAKCIE')return i.reply({content:'❌ Brak aktywnego egzaminu.',ephemeral:true});const q=Q[e.question];e.score+=(k===q[2]?1:0);e.question++;if(e.question>=Q.length){const pct=Math.round(e.score/Q.length*100),pass=pct>=70;e.status='ZAKONCZONY';e.percent=pct;e.result=pass?'ZDAŁ':'NIE ZDAŁ';e.finishedAt=new Date().toISOString();save();await i.update({embeds:[new EmbedBuilder().setTitle('🎓 EGZAMIN ZAKOŃCZONY').setDescription(`Kandydat: <@${i.user.id}>\nWynik: **${e.score}/${Q.length} (${pct}%)**\nMinimum: **70%**\nAutomatycznie: **${e.result}**\n\nKadra może zatwierdzić lub odrzucić wynik.`)],components:[new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId(`accept:${i.user.id}`).setLabel('Zatwierdź').setStyle(ButtonStyle.Success),new ButtonBuilder().setCustomId(`reject:${i.user.id}`).setLabel('Odrzuć').setStyle(ButtonStyle.Danger),new ButtonBuilder().setCustomId('close').setLabel('Zamknij').setStyle(ButtonStyle.Secondary))]});await post(i.guild,'examResults',new EmbedBuilder().setTitle('🎓 Wynik egzaminu').setDescription(`<@${i.user.id}> — **${e.score}/${Q.length} (${pct}%)** — **${e.result}**`));return sendLog(i.guild,'Egzamin zakończony',`${i.user} ${e.score}/${Q.length} (${pct}%)`);}save();await i.deferUpdate();return question(i.channel,i.user.id,e.question);}
function embedAction(title,target,actor,details){return new EmbedBuilder().setTitle(title).setDescription(`Funkcjonariusz: <@${target}>\nWykonał: <@${actor}>\n${details}`).setTimestamp();}
async function rankChange(i,down){if(!staff(i.member))return i.reply({content:'❌ Brak uprawnień kadry.',ephemeral:true});const u=i.options.getUser('osoba'),p=personnel(u),old=p.rank,newRank=i.options.getString('stopien'),reason=i.options.getString('powod');p.rank=newRank;p.history.push({type:down?'DEGRADACJA':'AWANS',oldRank:old,newRank,reason,by:i.user.id,at:new Date().toISOString()});save();action(down?'DEGRADACJA':'AWANS',u.id,i.user.id,`${old} → ${newRank}: ${reason}`);await post(i.guild,down?'demotions':'promotions',embedAction(down?'⬇️ Degradacja':'⬆️ Awans',u.id,i.user.id,`Stopień: **${old} → ${newRank}**\nPowód: ${reason}`));return i.reply({content:`✅ ${down?'Degradacja':'Awans'} zapisana: **${old} → ${newRank}**.`,ephemeral:true});}
async function personnelCard(i){const u=i.options.getUser('osoba')||i.user,p=personnel(u);const hist=p.history.slice(-10).reverse().map(x=>`${x.type}: ${x.oldRank||''} → ${x.newRank||''} ${x.reason?`— ${x.reason}`:''}`).join('\n')||'Brak';return i.reply({embeds:[new EmbedBuilder().setTitle(`👮 Karta funkcjonariusza — ${p.number}`).setDescription(`Osoba: <@${u.id}>\nStopień: **${p.rank}**\nPunkty: **${p.points}**\nNagany/postępowania: **${p.reprimands}**\nKwalifikacje: **${p.qualifications.length}**\nSzkolenia: **${p.trainings.length}**\n\n**Historia:**\n${hist}`)]});}

client.once('ready',async()=>{const rest=new REST({version:'10'}).setToken(TOKEN);await rest.put(Routes.applicationGuildCommands(CLIENT_ID,GUILD_ID),{body:commands});console.log(`Zalogowano jako ${client.user.tag} — kompletny system ŻW`);});
client.on('interactionCreate',async i=>{try{
if(i.isChatInputCommand()){
 const n=i.commandName;if(n==='zw-panel'){if(!staff(i.member))return i.reply({content:'❌ Tylko kadra może publikować panel.',ephemeral:true});const c=findChannel(i.guild,'panel');if(!c)return i.reply({content:'❌ Nie znaleziono istniejącego kanału panel-podania.',ephemeral:true});await c.send(panel());return i.reply({content:`✅ Panel opublikowany w ${c}.`,ephemeral:true});}
 if(n==='zw-zamknij'){if(!i.channel?.topic?.startsWith('ZW-TICKET:'))return i.reply({content:'❌ To nie jest ticket ŻW.',ephemeral:true});if(!staff(i.member)&&!i.channel.topic.endsWith(`:${i.user.id}`))return i.reply({content:'❌ Nie możesz zamknąć tego ticketu.',ephemeral:true});await i.reply({content:'🔒 Ticket zostanie zamknięty.',ephemeral:true});return i.channel.delete().catch(()=>{});}
 if(n==='zw-podania'){const a=Object.values(db.applications);return i.reply(`📋 Podania: **${a.length}** | oczekujące: **${a.filter(x=>x.status==='OCZEKUJE').length}** | przyjęte: **${a.filter(x=>x.status==='PRZYJĘTE').length}** | odrzucone: **${a.filter(x=>x.status==='ODRZUCONE').length}**`);}
 if(n==='zw-egzaminy'){const a=Object.values(db.exams);return i.reply(`📝 Egzaminy: **${a.length}** | zdane: **${a.filter(x=>x.result==='ZDAŁ').length}** | niezdane: **${a.filter(x=>x.result==='NIE ZDAŁ').length}**`);}
 if(n==='zw-raport'){const m=new ModalBuilder().setCustomId('report').setTitle('Raport służbowy');[['data','Data/miejsce',TextInputStyle.Short],['przebieg','Przebieg służby',TextInputStyle.Paragraph],['uwagi','Uwagi',TextInputStyle.Paragraph]].forEach(([id,l,s])=>m.addComponents(new ActionRowBuilder().addComponents(new TextInputBuilder().setCustomId(id).setLabel(l).setStyle(s).setRequired(true))));return i.showModal(m);}
 if(n==='zw-meldunek'){const m=new ModalBuilder().setCustomId('meldunek').setTitle('Meldunek służbowy');[['temat','Temat',TextInputStyle.Short],['tresc','Treść meldunku',TextInputStyle.Paragraph]].forEach(([id,l,s])=>m.addComponents(new ActionRowBuilder().addComponents(new TextInputBuilder().setCustomId(id).setLabel(l).setStyle(s).setRequired(true))));return i.showModal(m);}
 if(n==='zw-rozkaz'){if(!staff(i.member))return i.reply({content:'❌ Tylko kadra.',ephemeral:true});const t=i.options.getString('tytul'),x=i.options.getString('tresc');db.rozkazy.push({title:t,text:x,by:i.user.id,at:new Date().toISOString()});save();await post(i.guild,'orders',new EmbedBuilder().setTitle(`📜 Rozkaz: ${t}`).setDescription(x).setFooter({text:`Wydano przez ${i.user.username}`}));return i.reply({content:'✅ Rozkaz zapisany.',ephemeral:true});}
 if(n==='zw-plus'||n==='zw-minus'){if(!staff(i.member))return i.reply({content:'❌ Tylko kadra.',ephemeral:true});const u=i.options.getUser('osoba'),p=personnel(u),pts=i.options.getInteger('punkty'),why=i.options.getString('powod'),delta=n==='zw-plus'?pts:-pts;p.points+=delta;p.history.push({type:n==='zw-plus'?'PLUS':'MINUS',points:delta,reason:why,by:i.user.id,at:new Date().toISOString()});save();action(n==='zw-plus'?'PLUS':'MINUS',u.id,i.user.id,`${delta}: ${why}`);await post(i.guild,n==='zw-plus'?'awards':'proceedings',embedAction(n==='zw-plus'?'➕ Plus':'➖ Minus',u.id,i.user.id,`Punkty: **${delta>0?'+':''}${delta}**\nPowód: ${why}`));return i.reply({content:`✅ Zapisano ${n==='zw-plus'?'plus':'minus'}: **${delta>0?'+':''}${delta}**.`,ephemeral:true});}
 if(n==='zw-awans')return rankChange(i,false);if(n==='zw-degradacja')return rankChange(i,true);if(n==='zw-funkcjonariusz')return personnelCard(i);
 if(n==='zw-wyroznienie'){if(!staff(i.member))return i.reply({content:'❌ Tylko kadra.',ephemeral:true});const u=i.options.getUser('osoba'),p=personnel(u),d=i.options.getString('opis');p.awards.push({description:d,by:i.user.id,at:new Date().toISOString()});p.history.push({type:'WYRÓŻNIENIE',description:d,by:i.user.id,at:new Date().toISOString()});save();await post(i.guild,'awards',embedAction('🏅 Wyróżnienie',u.id,i.user.id,d));return i.reply({content:'✅ Wyróżnienie zapisane.',ephemeral:true});}
 if(n==='zw-postepowanie'){if(!staff(i.member))return i.reply({content:'❌ Tylko kadra.',ephemeral:true});const u=i.options.getUser('osoba'),p=personnel(u),d=i.options.getString('opis');p.reprimands++;p.history.push({type:'POSTĘPOWANIE',description:d,by:i.user.id,at:new Date().toISOString()});db.actions.push({type:'POSTĘPOWANIE',target:u.id,actor:i.user.id,details:d,at:new Date().toISOString()});save();await post(i.guild,'proceedings',embedAction('⚠️ Postępowanie',u.id,i.user.id,d));return i.reply({content:'✅ Postępowanie zapisane.',ephemeral:true});}
 if(n==='zw-szkolenie'){if(!staff(i.member))return i.reply({content:'❌ Tylko kadra.',ephemeral:true});const u=i.options.getUser('osoba'),p=personnel(u),name=i.options.getString('nazwa'),result=i.options.getString('wynik');p.trainings.push({name,result,by:i.user.id,at:new Date().toISOString()});p.history.push({type:'SZKOLENIE',description:`${name} — ${result}`,by:i.user.id,at:new Date().toISOString()});save();await post(i.guild,'trainings',embedAction('🎓 Ukończone szkolenie',u.id,i.user.id,`Szkolenie: **${name}**\nWynik: **${result}**`));return i.reply({content:'✅ Szkolenie zapisane.',ephemeral:true});}
 if(n==='zw-szkolenie-utworz'){if(!staff(i.member))return i.reply({content:'❌ Tylko kadra.',ephemeral:true});const name=i.options.getString('nazwa'),desc=i.options.getString('opis');db.trainings.push({name,description:desc,by:i.user.id,at:new Date().toISOString()});save();await post(i.guild,'trainings',new EmbedBuilder().setTitle(`🎓 Szkolenie: ${name}`).setDescription(desc).setFooter({text:`Organizator: ${i.user.username}`}));return i.reply({content:'✅ Szkolenie opublikowane.',ephemeral:true});}
 if(n==='zw-material'){if(!staff(i.member))return i.reply({content:'❌ Tylko kadra.',ephemeral:true});const t=i.options.getString('tytul'),x=i.options.getString('tresc');await post(i.guild,'materials',new EmbedBuilder().setTitle(`📚 Materiał: ${t}`).setDescription(x).setFooter({text:`Dodano przez ${i.user.username}`}));return i.reply({content:'✅ Materiał opublikowany.',ephemeral:true});}
 if(n==='zw-kwalifikacja'){if(!staff(i.member))return i.reply({content:'❌ Tylko kadra.',ephemeral:true});const u=i.options.getUser('osoba'),p=personnel(u),name=i.options.getString('nazwa'),status=i.options.getString('status');p.qualifications.push({name,status,by:i.user.id,at:new Date().toISOString()});p.history.push({type:'KWALIFIKACJA',description:`${name} — ${status}`,by:i.user.id,at:new Date().toISOString()});db.qualifications.push({userId:u.id,name,status,by:i.user.id,at:new Date().toISOString()});save();await post(i.guild,'qualifications',embedAction('📋 Kwalifikacja',u.id,i.user.id,`**${name}** — ${status}`));return i.reply({content:'✅ Kwalifikacja zapisana.',ephemeral:true});}
 if(n==='zw-egzamin-szkolenie'){if(!staff(i.member))return i.reply({content:'❌ Tylko kadra.',ephemeral:true});const u=i.options.getUser('osoba'),p=personnel(u),name=i.options.getString('nazwa'),pct=i.options.getInteger('procent'),result=pct>=70?'ZDAŁ':'NIE ZDAŁ';db.trainingExams.push({userId:u.id,name,pct,result,by:i.user.id,at:new Date().toISOString()});p.history.push({type:'EGZAMIN SZKOLENIOWY',description:`${name} — ${pct}% — ${result}`,by:i.user.id,at:new Date().toISOString()});save();await post(i.guild,'examResults',embedAction('📝 Wynik egzaminu szkoleniowego',u.id,i.user.id,`Egzamin: **${name}**\nWynik: **${pct}% — ${result}**`));return i.reply({content:`✅ Wynik zapisany: **${pct}% — ${result}**.`,ephemeral:true});}
 if(n==='zw-sluzba'){const p=personnel(i.user),a=i.options.getString('akcja'),note=i.options.getString('notatka')||'';if(a==='start'){if(db.duty[i.user.id]?.start)return i.reply({content:'❌ Masz już rozpoczętą służbę.',ephemeral:true});db.duty[i.user.id]={start:Date.now(),note};}else{const d=db.duty[i.user.id];if(!d?.start)return i.reply({content:'❌ Nie masz rozpoczętej służby.',ephemeral:true});const mins=Math.max(0,Math.round((Date.now()-d.start)/60000));p.dutyMinutes+=mins;db.duty[i.user.id]={last:Date.now(),minutes:mins,note};p.history.push({type:'SŁUŻBA',description:`${mins} min`,at:new Date().toISOString()});}save();return i.reply({content:a==='start'?'🟢 Służba rozpoczęta.':`🔴 Służba zakończona. Czas: **${db.duty[i.user.id].minutes||0} min**.`,ephemeral:true});}
 if(n==='zw-archiwum'){if(!staff(i.member))return i.reply({content:'❌ Tylko kadra.',ephemeral:true});const p=personnel(i.options.getUser('osoba'));const h=p.history.slice(-20).reverse().map(x=>`• **${x.type}** — ${x.description||`${x.oldRank||''} → ${x.newRank||''}`} — <t:${Math.floor(new Date(x.at).getTime()/1000)}:R>`).join('\n')||'Brak historii';return i.reply({embeds:[new EmbedBuilder().setTitle(`📁 Archiwum — ${p.number}`).setDescription(h)]});}
 if(n==='zw-statystyki'){const people=Object.values(db.personnel);return i.reply({embeds:[new EmbedBuilder().setTitle('📊 Statystyki ŻW').setDescription(`Funkcjonariusze: **${people.length}**\nPodania: **${Object.keys(db.applications).length}**\nEgzaminy rekrutacyjne: **${Object.keys(db.exams).length}**\nRaporty: **${db.reports.length}**\nMeldunki: **${db.meldunki.length}**\nRozkazy: **${db.rozkazy.length}**\nSzkolenia: **${db.trainings.length}**\nEgzaminy szkoleniowe: **${db.trainingExams.length}**\nKwalifikacje: **${db.qualifications.length}**`)]});}
}
if(i.isButton()){if(i.customId==='new_app')return ticket(i,'application');if(i.customId==='new_exam')return ticket(i,'exam');if(i.customId==='exam_start')return startExam(i);if(i.customId==='close')return i.channel?.delete().catch(()=>{});if(i.customId.startsWith('ans:'))return answer(i,Number(i.customId.split(':')[1]));if(i.customId.startsWith('accept:')||i.customId.startsWith('reject:')){if(!staff(i.member))return i.reply({content:'❌ Tylko kadra.',ephemeral:true});const uid=i.customId.split(':')[1];if(db.exams[uid]){db.exams[uid].staffResult=i.customId.startsWith('accept:')?'ZATWIERDZONY':'ODRZUCONY';db.exams[uid].staffBy=i.user.id;save();}return i.reply({content:'✅ Decyzja zapisana.',ephemeral:true});}}
if(i.isModalSubmit()){if(i.customId.startsWith('app:')){const ch=i.customId.split(':')[1];db.applications[i.user.id]={userId:i.user.id,channelId:ch,wiek:i.fields.getTextInputValue('wiek'),dane:i.fields.getTextInputValue('dane'),exp:i.fields.getTextInputValue('exp'),mot:i.fields.getTextInputValue('mot'),czas:i.fields.getTextInputValue('czas'),status:'OCZEKUJE',at:new Date().toISOString()};save();const c=i.guild.channels.cache.get(ch);await c?.send({embeds:[new EmbedBuilder().setTitle('📋 Nowe podanie').setDescription(`Kandydat: <@${i.user.id}>\n**Wiek:** ${db.applications[i.user.id].wiek}\n**Dane RP:** ${db.applications[i.user.id].dane}\n**Doświadczenie:** ${db.applications[i.user.id].exp}\n**Motywacja:** ${db.applications[i.user.id].mot}\n**Dyspozycyjność:** ${db.applications[i.user.id].czas}`)]});await post(i.guild,'applications',new EmbedBuilder().setTitle('📋 Nowe podanie').setDescription(`Kandydat: <@${i.user.id}>\nStatus: **OCZEKUJE**`));return i.reply({content:'✅ Podanie zostało zapisane.',ephemeral:true});}
if(i.customId==='report'){db.reports.push({userId:i.user.id,data:i.fields.getTextInputValue('data'),przebieg:i.fields.getTextInputValue('przebieg'),uwagi:i.fields.getTextInputValue('uwagi'),at:new Date().toISOString()});save();await post(i.guild,'reports',new EmbedBuilder().setTitle('📋 Raport służbowy').setDescription(`Autor: <@${i.user.id}>\n**Data/miejsce:** ${i.fields.getTextInputValue('data')}\n**Przebieg:** ${i.fields.getTextInputValue('przebieg')}\n**Uwagi:** ${i.fields.getTextInputValue('uwagi')}`));return i.reply({content:'✅ Raport zapisany.',ephemeral:true});}
if(i.customId==='meldunek'){db.meldunki.push({userId:i.user.id,temat:i.fields.getTextInputValue('temat'),tresc:i.fields.getTextInputValue('tresc'),at:new Date().toISOString()});save();await post(i.guild,'meldunki',new EmbedBuilder().setTitle(`📡 Meldunek — ${i.fields.getTextInputValue('temat')}`).setDescription(`Autor: <@${i.user.id}>\n${i.fields.getTextInputValue('tresc')}`));return i.reply({content:'✅ Meldunek zapisany.',ephemeral:true});}}
}catch(e){console.error(e);if(!i.replied&&!i.deferred)await i.reply({content:'❌ Wystąpił błąd systemu.',ephemeral:true}).catch(()=>{});}}
);
client.login(TOKEN);
