require('dotenv').config();
const { Client, GatewayIntentBits, PermissionsBitField, ChannelType, REST, Routes, SlashCommandBuilder, EmbedBuilder, ActionRowBuilder, ButtonBuilder, ButtonStyle, ModalBuilder, TextInputBuilder, TextInputStyle } = require('discord.js');
const db = require('./database');
const { TOKEN, CLIENT_ID, GUILD_ID, TICKET_CATEGORY_ID, EXAM_CATEGORY_ID, STAFF_ROLE_IDS, LOG_CHANNEL_ID } = process.env;
if (!TOKEN || !CLIENT_ID || !GUILD_ID) throw new Error('Brak TOKEN, CLIENT_ID lub GUILD_ID w .env');
const client = new Client({ intents: [GatewayIntentBits.Guilds] });
const P = PermissionsBitField.Flags;
const staffIds = (STAFF_ROLE_IDS || '').split(',').map(x => x.trim()).filter(Boolean);
const QUESTIONS = [
 {q:'Jaki jest podstawowy cel Żandarmerii Wojskowej?',a:['Zapewnianie przestrzegania dyscypliny wojskowej','Prowadzenie wyłącznie szkoleń sportowych','Obsługa administracji cywilnej','Kontrola ruchu lotniczego'],c:0},
 {q:'Gdzie ŻW może chronić porządek publiczny?',a:['Tylko poza jednostkami','Na terenach i obiektach jednostek wojskowych oraz w miejscach publicznych','Wyłącznie w koszarach','Tylko podczas wojny'],c:1},
 {q:'Jak należy wykonać polecenie przełożonego w RP?',a:['Zignorować','Zgodnie z regulaminem i zasadami RP','Opublikować publicznie','Przekazać cywilowi'],c:1},
 {q:'Co oznacza RP?',a:['Real Play','RolePlay','Rapid Patrol','Regulamin Personalny'],c:1},
 {q:'Jak zachować się podczas kontroli?',a:['Prowokować','Zachować kulturę, opanowanie i działać według procedury RP','Odmówić przedstawienia się','Opuścić miejsce bez powodu'],c:1},
 {q:'Czy informacje kadrowe wolno przekazywać osobom nieuprawnionym?',a:['Tak','Nie','Tylko poza Discordem','Zawsze podczas patrolu'],c:1},
 {q:'Jaki powinien być komunikat radiowy?',a:['Chaos i długi','Krótki, jasny i rzeczowy','Same emotikony','Bez identyfikacji'],c:1},
 {q:'Co najlepiej opisuje dyscyplinę służbową?',a:['Wykonywanie tylko łatwych zadań','Przestrzeganie poleceń, regulaminów i zasad służby','Brak odpowiedzialności','Wyłącznie mundur'],c:1},
 {q:'Co zrobić, gdy sytuacja przekracza możliwości patrolu?',a:['Udawać, że nic się nie stało','Wezwać wsparcie i przekazać rzeczowy meldunek','Opuścić serwer','Usunąć dowody'],c:1},
 {q:'Jak powinien zachować się kandydat podczas egzaminu?',a:['Korzystać z podpowiedzi','Samodzielnie i uczciwie odpowiadać','Spamować','Ignorować egzaminatora'],c:1}
];
const commands=[
 new SlashCommandBuilder().setName('zw-panel').setDescription('Publikuje panel podań i egzaminów ŻW.'),
 new SlashCommandBuilder().setName('zw-zamknij').setDescription('Zamyka aktualny ticket ŻW.'),
 new SlashCommandBuilder().setName('zw-podania').setDescription('Pokazuje liczbę oczekujących podań.'),
 new SlashCommandBuilder().setName('zw-egzaminy').setDescription('Pokazuje liczbę zakończonych egzaminów.')
].map(x=>x.toJSON());
function isStaff(m){return m.permissions.has(P.Administrator)||staffIds.some(id=>m.roles.cache.has(id));}
function safeName(s){return s.toLowerCase().replace(/[^a-z0-9_-]/gi,'-').slice(0,65)||'kandydat';}
function ticketType(c){return c?.topic?.startsWith('ZW-TICKET:')?c.topic.split(':')[1]:null;}
function panel(){return {embeds:[new EmbedBuilder().setColor(0x1f2937).setTitle('🇵🇱 ŻANDARMERIA WOJSKOWA — REKRUTACJA').setDescription('Wybierz odpowiednią opcję.\n\n🎓 **Podanie** — formularz rekrutacyjny w prywatnym tickecie.\n📝 **Egzamin** — prywatny ticket i automatyczny egzamin.\n\nNie twórz kilku ticketów tego samego typu.')],components:[new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('ticket_application').setLabel('Złóż podanie').setEmoji('🎓').setStyle(ButtonStyle.Primary),new ButtonBuilder().setCustomId('ticket_exam').setLabel('Egzamin').setEmoji('📝').setStyle(ButtonStyle.Success))]};}
async function sendLog(guild,title,description){if(!LOG_CHANNEL_ID)return;const c=guild.channels.cache.get(LOG_CHANNEL_ID);if(c?.isTextBased())await c.send({embeds:[new EmbedBuilder().setColor(0x5865f2).setTitle(title).setDescription(description).setTimestamp()]}).catch(()=>{});}
async function createTicket(i,type){const categoryId=type==='exam'?EXAM_CATEGORY_ID:TICKET_CATEGORY_ID;if(!categoryId)return i.reply({content:'❌ Ustaw TICKET_CATEGORY_ID / EXAM_CATEGORY_ID w .env.',ephemeral:true});const old=i.guild.channels.cache.find(c=>c.type===ChannelType.GuildText&&c.topic===`ZW-TICKET:${type}:${i.user.id}`);if(old)return i.reply({content:`❌ Masz już ticket: ${old}`,ephemeral:true});const ow=[{id:i.guild.roles.everyone.id,deny:[P.ViewChannel]},{id:i.user.id,allow:[P.ViewChannel,P.SendMessages,P.ReadMessageHistory]}];for(const id of staffIds)ow.push({id,allow:[P.ViewChannel,P.SendMessages,P.ReadMessageHistory,P.ManageMessages]});ow.push({id:i.guild.members.me.id,allow:[P.ViewChannel,P.SendMessages,P.ReadMessageHistory,P.ManageChannels,P.ManageMessages]});const c=await i.guild.channels.create({name:`${type==='exam'?'egzamin':'podanie'}-${safeName(i.user.username)}`,type:ChannelType.GuildText,parent:categoryId,topic:`ZW-TICKET:${type}:${i.user.id}`,permissionOverwrites:ow});await i.reply({content:`✅ Ticket utworzony: ${c}`,ephemeral:true});
 if(type==='application'){const modal=new ModalBuilder().setCustomId(`application:${c.id}`).setTitle('Podanie do Żandarmerii Wojskowej');const f=[['wiek','Wiek','Wiek postaci',TextInputStyle.Short],['imie','Imię i nazwisko RP','Dane postaci',TextInputStyle.Short],['doswiadczenie','Doświadczenie','Doświadczenie RP / służby',TextInputStyle.Paragraph],['motywacja','Motywacja','Dlaczego ŻW?',TextInputStyle.Paragraph],['dyspozycyjnosc','Dyspozycyjność','Kiedy możesz pełnić służbę?',TextInputStyle.Paragraph]];modal.addComponents(...f.map(([id,label,ph,style])=>new ActionRowBuilder().addComponents(new TextInputBuilder().setCustomId(id).setLabel(label).setPlaceholder(ph).setStyle(style).setRequired(true).setMaxLength(1000))));setTimeout(()=>i.showModal(modal).catch(()=>{}),350);
 }else{await c.send({content:`<@${i.user.id}>`,embeds:[new EmbedBuilder().setColor(0x22c55e).setTitle('📝 EGZAMIN ŻW').setDescription('Egzamin składa się z 10 pytań. Wybierasz jedną odpowiedź. Minimum zaliczenia: **70%**.\n\nOdpowiadaj samodzielnie.')],components:[new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('exam_start').setLabel('Rozpocznij egzamin').setStyle(ButtonStyle.Success),new ButtonBuilder().setCustomId('ticket_close').setLabel('Zamknij ticket').setStyle(ButtonStyle.Danger))]});await sendLog(i.guild,'🎫 Nowy ticket egzaminacyjny',`${i.user} → ${c}`);}}
async function closeTicket(c,reason){await c.send({embeds:[new EmbedBuilder().setColor(0xef4444).setTitle('🔒 Ticket zamknięty').setDescription(reason).setTimestamp()]}).catch(()=>{});setTimeout(()=>c.delete('ŻW BOT — zamknięcie ticketu').catch(()=>{}),2000);}
async function sendQuestion(channel,userId,n){const q=QUESTIONS[n];const row=new ActionRowBuilder();q.a.forEach((x,k)=>row.addComponents(new ButtonBuilder().setCustomId(`answer:${k}`).setLabel(`${String.fromCharCode(65+k)}. ${x}`.slice(0,80)).setStyle(ButtonStyle.Secondary)));await channel.send({content:`<@${userId}>`,embeds:[new EmbedBuilder().setColor(0x22c55e).setTitle(`📝 EGZAMIN ŻW • ${n+1}/${QUESTIONS.length}`).setDescription(q.q)],components:[row]});}
async function answerExam(i,index){const e=db.getExam(i.user.id);if(!e||e.channelId!==i.channel.id||e.status!=='W_TRAKCIE')return i.reply({content:'❌ Nie masz aktywnego egzaminu.',ephemeral:true});const q=QUESTIONS[e.question];const score=e.score+(index===q.c?1:0);const next=e.question+1;const answers=[...(e.answers||[]),index];if(next>=QUESTIONS.length){const percent=Math.round(score/QUESTIONS.length*100);db.updateExam(i.user.id,{question:next,score,answers,status:'ZAKOŃCZONY',percent,finishedAt:new Date().toISOString()});const passed=percent>=70;await i.update({content:'',embeds:[new EmbedBuilder().setColor(passed?0x22c55e:0xef4444).setTitle('🎓 EGZAMIN ZAKOŃCZONY').setDescription(`Kandydat: <@${i.user.id}>\nWynik: **${score}/${QUESTIONS.length} (${percent}%)**\nMinimum: **70%**\nStatus automatyczny: **${passed?'ZDAŁ':'NIE ZDAŁ'}**\n\nKadra może zatwierdzić wynik.`)],components:[new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId(`exam_accept:${i.user.id}`).setLabel('Zatwierdź wynik').setStyle(ButtonStyle.Success),new ButtonBuilder().setCustomId(`exam_reject:${i.user.id}`).setLabel('Odrzuć wynik').setStyle(ButtonStyle.Danger),new ButtonBuilder().setCustomId('ticket_close').setLabel('Zamknij').setStyle(ButtonStyle.Secondary))]});return sendLog(i.guild,'🎓 Egzamin zakończony',`${i.user} — **${score}/${QUESTIONS.length} (${percent}%)**`);}db.updateExam(i.user.id,{question:next,score,answers});await i.update({content:`✅ Odpowiedź zapisana. Wynik: **${score}/${next}**`,embeds:[],components:[]});setTimeout(()=>sendQuestion(i.channel,i.user.id,next),500);}
client.once('ready',async()=>{const rest=new REST({version:'10'}).setToken(TOKEN);await rest.put(Routes.applicationGuildCommands(CLIENT_ID,GUILD_ID),{body:commands});console.log(`ŻW BOT online: ${client.user.tag}`);});
client.on('interactionCreate',async i=>{try{
 if(i.isChatInputCommand()){if(i.commandName==='zw-panel'){if(!isStaff(i.member))return i.reply({content:'❌ Brak uprawnień.',ephemeral:true});await i.channel.send(panel());return i.reply({content:'✅ Panel wysłany.',ephemeral:true});}if(i.commandName==='zw-zamknij'){if(!isStaff(i.member)||!ticketType(i.channel))return i.reply({content:'❌ Brak uprawnień lub to nie jest ticket.',ephemeral:true});await i.reply('🔒 Zamykam…');return closeTicket(i.channel,`Zamknięte przez ${i.user.tag}`);}if(i.commandName==='zw-podania'){if(!isStaff(i.member))return i.reply({content:'❌ Brak uprawnień.',ephemeral:true});return i.reply({content:`📋 Oczekujące podania: **${db.allApplications().filter(x=>x.status==='NOWE').length}**`,ephemeral:true});}if(i.commandName==='zw-egzaminy'){if(!isStaff(i.member))return i.reply({content:'❌ Brak uprawnień.',ephemeral:true});return i.reply({content:`🎓 Egzaminy zakończone: **${db.allExams().filter(x=>x.status==='ZAKOŃCZONY').length}**`,ephemeral:true});}}
 if(i.isButton()){if(i.customId==='ticket_application')return createTicket(i,'application');if(i.customId==='ticket_exam')return createTicket(i,'exam');if(i.customId==='ticket_close'){if(!isStaff(i.member))return i.reply({content:'❌ Tylko kadra może zamknąć ticket.',ephemeral:true});await i.reply('🔒 Zamykam ticket…');return closeTicket(i.channel,`Zamknięte przez ${i.user.tag}`);}if(i.customId==='exam_start'){const e=db.getExam(i.user.id);if(e?.status==='W_TRAKCIE')return i.reply({content:'❌ Egzamin jest już rozpoczęty.',ephemeral:true});db.createExam(i.user.id,{discordId:i.user.id,channelId:i.channel.id,question:0,score:0,status:'W_TRAKCIE',answers:[],startedAt:new Date().toISOString()});await i.reply({content:'▶️ Egzamin rozpoczęty.',ephemeral:true});return sendQuestion(i.channel,i.user.id,0);}if(i.customId.startsWith('answer:'))return answerExam(i,Number(i.customId.split(':')[1]));if(i.customId.startsWith('exam_accept:')||i.customId.startsWith('exam_reject:')){if(!isStaff(i.member))return i.reply({content:'❌ Tylko kadra.',ephemeral:true});const id=i.customId.split(':')[1],ok=i.customId.startsWith('exam_accept:');db.updateExam(id,{status:ok?'ZALICZONY':'NIEZALICZONY',reviewedBy:i.user.id,reviewedAt:new Date().toISOString()});await i.reply(ok?'✅ Wynik zatwierdzony.':'❌ Wynik odrzucony.');return sendLog(i.guild,'🎓 Decyzja egzaminacyjna',`Kandydat: <@${id}>\nDecyzja: **${ok?'ZALICZONY':'NIEZALICZONY'}**\nKadra: ${i.user}`);}if(i.customId.startsWith('application_accept:')||i.customId.startsWith('application_reject:')){if(!isStaff(i.member))return i.reply({content:'❌ Tylko kadra.',ephemeral:true});const id=i.customId.split(':')[1],ok=i.customId.startsWith('application_accept:');db.updateApplication(id,{status:ok?'PRZYJĘTE':'ODRZUCONE',reviewedBy:i.user.id,reviewedAt:new Date().toISOString()});await i.reply(ok?'✅ Podanie przyjęte.':'❌ Podanie odrzucone.');return sendLog(i.guild,'📋 Decyzja w sprawie podania',`Kandydat: <@${id}>\nDecyzja: **${ok?'PRZYJĘTE':'ODRZUCONE'}**\nKadra: ${i.user}`);}}
 if(i.isModalSubmit()&&i.customId.startsWith('application:')){const channelId=i.customId.split(':')[1],channel=i.guild.channels.cache.get(channelId);const a={discordId:i.user.id,channelId,age:i.fields.getTextInputValue('wiek'),name:i.fields.getTextInputValue('imie'),experience:i.fields.getTextInputValue('doswiadczenie'),motivation:i.fields.getTextInputValue('motywacja'),availability:i.fields.getTextInputValue('dyspozycyjnosc'),status:'NOWE',createdAt:new Date().toISOString()};db.createApplication(i.user.id,a);const e=new EmbedBuilder().setColor(0x3b82f6).setTitle('📋 PODANIE — ŻANDARMERIA WOJSKOWA').addFields({name:'Kandydat',value:`<@${i.user.id}>`,inline:true},{name:'Wiek',value:a.age,inline:true},{name:'Imię i nazwisko RP',value:a.name},{name:'Doświadczenie',value:a.experience.slice(0,1024)},{name:'Motywacja',value:a.motivation.slice(0,1024)},{name:'Dyspozycyjność',value:a.availability.slice(0,1024)}).setTimestamp();await i.reply({content:'✅ Podanie zapisane. Poczekaj na decyzję kadry.',ephemeral:true});if(channel)await channel.send({embeds:[e],components:[new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId(`application_accept:${i.user.id}`).setLabel('Przyjmij').setStyle(ButtonStyle.Success),new ButtonBuilder().setCustomId(`application_reject:${i.user.id}`).setLabel('Odrzuć').setStyle(ButtonStyle.Danger),new ButtonBuilder().setCustomId('ticket_close').setLabel('Zamknij').setStyle(ButtonStyle.Secondary))]});await sendLog(i.guild,'📝 Nowe podanie ŻW',`Kandydat: ${i.user}\nTicket: ${channel||channelId}`);}
 }catch(e){console.error(e);if(!i.replied&&!i.deferred)await i.reply({content:'❌ Wystąpił błąd. Sprawdź logi.',ephemeral:true}).catch(()=>{});}});
client.login(TOKEN);
