require('dotenv').config();
const fs=require('node:fs'),path=require('node:path');
const {Client,GatewayIntentBits,PermissionsBitField,ChannelType,REST,Routes,SlashCommandBuilder,EmbedBuilder,ActionRowBuilder,ButtonBuilder,ButtonStyle,ModalBuilder,TextInputBuilder,TextInputStyle}=require('discord.js');
const {TOKEN,CLIENT_ID,GUILD_ID,STAFF_ROLE_IDS,LOG_CHANNEL_ID}=process.env;if(!TOKEN||!CLIENT_ID||!GUILD_ID)throw Error('Brak TOKEN, CLIENT_ID lub GUILD_ID w .env');
const client=new Client({intents:[GatewayIntentBits.Guilds]}),P=PermissionsBitField.Flags,staffIds=(STAFF_ROLE_IDS||'').split(',').map(x=>x.trim()).filter(Boolean);
const file=path.join(process.cwd(),'data','zw-final.json'),blank={next:1,people:{},applications:[],exams:[],reports:[],meldunki:[],orders:[],actions:[],proceedings:[],awards:[],trainings:[],trainingExams:[],materials:[],qualifications:[],duty:{}};
fs.mkdirSync(path.dirname(file),{recursive:true});if(!fs.existsSync(file))fs.writeFileSync(file,JSON.stringify(blank,null,2));let db;try{db={...blank,...JSON.parse(fs.readFileSync(file,'utf8'))}}catch{db=structuredClone(blank)}function save(){fs.writeFileSync(file,JSON.stringify(db,null,2))}
const norm=s=>String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]/g,'');
const CH={panel:['panel-podania'],requirements:['wymagania-rekrutacji'],apps:['podania-wewnetrzne'],recruit:['wyniki-rekrutacji'],candidateExam:['egzamin-kandydata'],status:['status-rekrutacji'],reports:['raporty','raporty-sluzbowe','raport'],schedule:['grafik-sluzby'],radio:['lacznosc'],patrols:['patrole'],personnel:['stan-osobowy'],cases:['sprawy-kadrowe'],promotions:['awanse'],demotions:['degradacje'],proceedings:['postepowania'],awards:['wyroznienia'],archive:['archiwum-kadr'],materials:['materialy'],trainings:['szkolenia'],exams:['egzaminy'],examResults:['wyniki-egzaminow'],qualifications:['kwalifikacje'],command:['komenda-glowna'],units:['wydzial']};
const find=(g,k)=>g.channels.cache.find(c=>c.type===ChannelType.GuildText&&(CH[k]||[k]).map(norm).includes(norm(c.name)));const cat=g=>g.channels.cache.find(c=>c.type===ChannelType.GuildCategory&&norm(c.name)==='rekrutacjakandydat');const staff=m=>!!m&&(m.permissions.has(P.Administrator)||staffIds.some(x=>m.roles.cache.has(x)));
function person(u){if(!db.people[u.id])db.people[u.id]={id:u.id,name:u.username,number:`ZW-${String(db.next++).padStart(4,'0')}`,rank:'Kandydat',plus:0,minus:0,reprimands:0,awards:[],history:[],qualifications:[],trainings:[],duty:0};save();return db.people[u.id]}
async function post(g,k,title,text){const c=find(g,k);if(c)await c.send({embeds:[new EmbedBuilder().setTitle(title).setDescription(text).setTimestamp()]}).catch(()=>{});return c}
async function audit(g,title,text){if(!LOG_CHANNEL_ID)return;const c=g.channels.cache.get(LOG_CHANNEL_ID);if(c?.isTextBased())await c.send({embeds:[new EmbedBuilder().setTitle(title).setDescription(text).setTimestamp()]}).catch(()=>{})}
const ranks=['Kandydat','Szeregowy','Starszy szeregowy','Kapral','Plutonowy','Sierżant','Starszy sierżant','Chorąży','Podporucznik','Porucznik','Kapitan','Major','Podpułkownik','Pułkownik','Generał brygady','Generał dywizji','Generał broni'],ranksC=ranks.map(x=>({name:x,value:x}));
const Q=[['Podstawowy cel ŻW?',['Przestrzeganie dyscypliny wojskowej','Sport','Administracja cywilna','Kontrola lotnicza'],0],['Gdzie ŻW wykonuje zadania?',['Tylko poza jednostkami','Na terenach i obiektach wojskowych oraz w zakresie prawa w miejscach publicznych','Tylko koszary','Tylko wojna'],1],['Jak wykonywać polecenia w RP?',['Ignorować','Zgodnie z regulaminem i zasadami RP','Publikować','Przekazywać losowym osobom'],1],['Co oznacza RP?',['Real Play','RolePlay','Rapid Patrol','Regulamin Personalny'],1],['Kontrola RP?',['Prowokować','Spokojnie, kulturalnie i proceduralnie','Uciekać','Spamować'],1],['Informacje kadrowe dla nieuprawnionych?',['Tak','Nie','Zawsze','Poza Discordem'],1],['Dobry meldunek radiowy?',['Chaotyczny','Krótki, jasny i rzeczowy','Same emoji','Bez informacji'],1],['Dyscyplina służbowa?',['Dowolność','Przestrzeganie poleceń i regulaminów','Tylko mundur','Brak odpowiedzialności'],1],['Brak możliwości patrolu?',['Nic','Wezwać wsparcie i złożyć meldunek','Odejść','Usunąć dokumenty'],1],['Egzamin?',['Podpowiedzi','Samodzielnie i uczciwie','Spam','Ignorowanie'],1]];
const cmd=(n,d)=>new SlashCommandBuilder().setName(n).setDescription(d);const C=[
cmd('zw-panel','Publikuje panel rekrutacyjny'),cmd('zw-zamknij','Zamyka ticket'),cmd('zw-podania','Statystyki podań'),cmd('zw-egzaminy','Statystyki egzaminów'),
cmd('zw-raport','Złóż raport').addStringOption(o=>o.setName('tresc').setDescription('Treść').setRequired(true)),cmd('zw-meldunek','Złóż meldunek').addStringOption(o=>o.setName('tresc').setDescription('Treść').setRequired(true)),cmd('zw-rozkaz','Dodaj rozkaz').addStringOption(o=>o.setName('tytul').setDescription('Tytuł').setRequired(true)).addStringOption(o=>o.setName('tresc').setDescription('Treść').setRequired(true)),
cmd('zw-plus','Dodaj plus').addUserOption(o=>o.setName('osoba').setDescription('Osoba').setRequired(true)).addIntegerOption(o=>o.setName('punkty').setDescription('Punkty').setMinValue(1).setMaxValue(100).setRequired(true)).addStringOption(o=>o.setName('powod').setDescription('Powód').setRequired(true)),cmd('zw-minus','Dodaj minus').addUserOption(o=>o.setName('osoba').setDescription('Osoba').setRequired(true)).addIntegerOption(o=>o.setName('punkty').setDescription('Punkty').setMinValue(1).setMaxValue(100).setRequired(true)).addStringOption(o=>o.setName('powod').setDescription('Powód').setRequired(true)),
cmd('zw-awans','Awans').addUserOption(o=>o.setName('osoba').setDescription('Osoba').setRequired(true)).addStringOption(o=>o.setName('stopien').setDescription('Stopień').setRequired(true).addChoices(...ranksC)).addStringOption(o=>o.setName('powod').setDescription('Powód').setRequired(true)),cmd('zw-degradacja','Degradacja').addUserOption(o=>o.setName('osoba').setDescription('Osoba').setRequired(true)).addStringOption(o=>o.setName('stopien').setDescription('Stopień').setRequired(true).addChoices(...ranksC)).addStringOption(o=>o.setName('powod').setDescription('Powód').setRequired(true)),
cmd('zw-wyroznienie','Wyróżnienie').addUserOption(o=>o.setName('osoba').setDescription('Osoba').setRequired(true)).addStringOption(o=>o.setName('opis').setDescription('Opis').setRequired(true)),cmd('zw-postepowanie','Postępowanie').addUserOption(o=>o.setName('osoba').setDescription('Osoba').setRequired(true)).addStringOption(o=>o.setName('opis').setDescription('Opis').setRequired(true)),cmd('zw-karta','Karta służbowa').addUserOption(o=>o.setName('osoba').setDescription('Osoba')),cmd('zw-kadra','Aktywna kadra'),cmd('zw-numer','Numer służbowy').addUserOption(o=>o.setName('osoba').setDescription('Osoba').setRequired(true)),cmd('zw-status','Status').addUserOption(o=>o.setName('osoba').setDescription('Osoba')),
cmd('zw-material','Dodaj materiał').addStringOption(o=>o.setName('tytul').setDescription('Tytuł').setRequired(true)).addStringOption(o=>o.setName('tresc').setDescription('Treść').setRequired(true)),cmd('zw-szkolenie','Zapisz szkolenie').addUserOption(o=>o.setName('osoba').setDescription('Osoba').setRequired(true)).addStringOption(o=>o.setName('nazwa').setDescription('Nazwa').setRequired(true)).addStringOption(o=>o.setName('wynik').setDescription('Wynik').setRequired(true)),cmd('zw-egzamin-szkolenie','Wynik egzaminu szkoleniowego').addUserOption(o=>o.setName('osoba').setDescription('Osoba').setRequired(true)).addStringOption(o=>o.setName('nazwa').setDescription('Nazwa').setRequired(true)).addIntegerOption(o=>o.setName('procent').setDescription('Procent').setMinValue(0).setMaxValue(100).setRequired(true)),cmd('zw-kwalifikacja','Kwalifikacja').addUserOption(o=>o.setName('osoba').setDescription('Osoba').setRequired(true)).addStringOption(o=>o.setName('nazwa').setDescription('Nazwa').setRequired(true)).addStringOption(o=>o.setName('status').setDescription('Status').setRequired(true)),cmd('zw-sluzba','Służba').addStringOption(o=>o.setName('akcja').setDescription('Akcja').setRequired(true).addChoices({name:'Rozpocznij',value:'start'},{name:'Zakończ',value:'stop'})),cmd('zw-archiwum','Archiwum kadrowe').addUserOption(o=>o.setName('osoba').setDescription('Osoba').setRequired(true)),cmd('zw-statystyki','Statystyki systemu')].map(x=>x.toJSON());
function panel(){return{embeds:[new EmbedBuilder().setTitle('🇵🇱 ŻANDARMERIA WOJSKOWA — REKRUTACJA').setDescription('🎓 **PODANIE** — formularz i prywatny ticket.\n📝 **EGZAMIN** — automatyczny egzamin rekrutacyjny.\n\nBot używa istniejących kanałów i ról.')],components:[new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('application').setLabel('Złóż podanie').setEmoji('🎓').setStyle(ButtonStyle.Primary),new ButtonBuilder().setCustomId('exam').setLabel('Egzamin').setEmoji('📝').setStyle(ButtonStyle.Success))]}}
async function examQuestion(ch,u,n){const q=Q[n],row=new ActionRowBuilder();q[1].forEach((a,k)=>row.addComponents(new ButtonBuilder().setCustomId(`q:${k}`).setLabel(`${String.fromCharCode(65+k)}. ${a}`.slice(0,80)).setStyle(ButtonStyle.Secondary)));await ch.send({content:`<@${u}>`,embeds:[new EmbedBuilder().setTitle(`📝 EGZAMIN ŻW ${n+1}/${Q.length}`).setDescription(q[0])],components:[row]})}
async function makeTicket(i,type,data){const parent=cat(i.guild);if(!parent)throw Error('Brak kategorii REKRUTACJA — KANDYDAT');const old=i.guild.channels.cache.find(c=>c.topic===`ZW-TICKET:${type}:${i.user.id}`);if(old)throw Error('Masz już otwarty ticket');const ow=[{id:i.guild.roles.everyone.id,deny:[P.ViewChannel]},{id:i.user.id,allow:[P.ViewChannel,P.SendMessages,P.ReadMessageHistory]}];staffIds.forEach(id=>ow.push({id,allow:[P.ViewChannel,P.SendMessages,P.ReadMessageHistory,P.ManageMessages]}));if(i.guild.members.me)ow.push({id:i.guild.members.me.id,allow:[P.ViewChannel,P.SendMessages,P.ReadMessageHistory,P.ManageChannels,P.ManageMessages]});const ch=await i.guild.channels.create({name:`${type==='application'?'podanie':'egzamin'}-${i.user.username.toLowerCase().replace(/[^a-z0-9-]/g,'-').slice(0,30)||'kandydat'}`,type:ChannelType.GuildText,parent:parent.id,topic:`ZW-TICKET:${type}:${i.user.id}`,permissionOverwrites:ow});if(type==='application'){db.applications.push({...data,user:i.user.id,channel:ch.id,status:'OCZEKUJE',at:new Date().toISOString()});save();await ch.send({embeds:[new EmbedBuilder().setTitle('📋 PODANIE ODEBRANE').setDescription(`Kandydat: <@${i.user.id}>\nWiek: ${data.wiek}\nDane RP: ${data.dane}\nDoświadczenie: ${data.doswiadczenie}\nMotywacja: ${data.motywacja}\nDyspozycyjność: ${data.dyspozycyjnosc}`)],components:[new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('app-accept').setLabel('Przyjmij').setStyle(ButtonStyle.Success),new ButtonBuilder().setCustomId('app-reject').setLabel('Odrzuć').setStyle(ButtonStyle.Danger),new ButtonBuilder().setCustomId('close').setLabel('Zamknij').setStyle(ButtonStyle.Secondary))]});await post(i.guild,'apps','📋 NOWE PODANIE',`<@${i.user.id}> — oczekuje na decyzję.`)}else{db.exams.push({user:i.user.id,channel:ch.id,q:0,score:0,status:'W_TRAKCIE',at:new Date().toISOString()});save();await ch.send({embeds:[new EmbedBuilder().setTitle('📝 EGZAMIN ŻW').setDescription('10 pytań • minimum 70%')],components:[new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('exam-start').setLabel('Rozpocznij').setStyle(ButtonStyle.Success),new ButtonBuilder().setCustomId('close').setLabel('Zamknij').setStyle(ButtonStyle.Danger))]})}return ch}
client.once('ready',async()=>{await new REST({version:'10'}).setToken(TOKEN).put(Routes.applicationGuildCommands(CLIENT_ID,GUILD_ID),{body:C});console.log(`ŻW BOT online: ${client.user.tag}`)});
client.on('interactionCreate',async i=>{try{
if(i.isButton()&&i.customId==='application'){const m=new ModalBuilder().setCustomId('app-modal').setTitle('Podanie do ŻW');[['wiek','Wiek'],['dane','Imię i nazwisko RP'],['doswiadczenie','Doświadczenie'],['motywacja','Motywacja'],['dyspozycyjnosc','Dyspozycyjność']].forEach(([id,l])=>m.addComponents(new ActionRowBuilder().addComponents(new TextInputBuilder().setCustomId(id).setLabel(l).setStyle(id==='wiek'||id==='dane'?TextInputStyle.Short:TextInputStyle.Paragraph).setRequired(true).setMaxLength(1000))));return i.showModal(m)}
if(i.isButton()&&i.customId==='exam'){try{const ch=await makeTicket(i,'exam');return i.reply({content:`✅ Utworzono ${ch}`,ephemeral:true})}catch(e){return i.reply({content:`❌ ${e.message}`,ephemeral:true})}}
if(i.isModalSubmit()&&i.customId==='app-modal'){try{const d={wiek:i.fields.getTextInputValue('wiek'),dane:i.fields.getTextInputValue('dane'),doswiadczenie:i.fields.getTextInputValue('doswiadczenie'),motywacja:i.fields.getTextInputValue('motywacja'),dyspozycyjnosc:i.fields.getTextInputValue('dyspozycyjnosc')};const ch=await makeTicket(i,'application',d);return i.reply({content:`✅ Utworzono ticket podania: ${ch}`,ephemeral:true})}catch(e){return i.reply({content:`❌ ${e.message}`,ephemeral:true})}}
if(i.isButton()&&i.customId==='exam-start'){const e=db.exams.find(x=>x.channel===i.channel.id&&x.user===i.user.id);if(!e)return i.reply({content:'❌ Brak egzaminu.',ephemeral:true});await i.reply({content:'✅ Rozpoczęto.',ephemeral:true});return examQuestion(i.channel,i.user.id,0)}
if(i.isButton()&&i.customId.startsWith('q:')){const e=db.exams.find(x=>x.channel===i.channel.id&&x.user===i.user.id&&x.status==='W_TRAKCIE');if(!e)return i.reply({content:'❌ Brak aktywnego egzaminu.',ephemeral:true});if(Number(i.customId.slice(2))===Q[e.q][2])e.score++;e.q++;if(e.q>=Q.length){e.status='ZAKONCZONY';e.percent=Math.round(e.score/Q.length*100);save();await i.update({embeds:[new EmbedBuilder().setTitle('🎓 EGZAMIN ZAKOŃCZONY').setDescription(`Wynik: **${e.score}/${Q.length} (${e.percent}%)**\nMinimum: **70%**\n**${e.percent>=70?'ZDAŁ':'NIE ZDAŁ'}**`)],components:[]});return post(i.guild,'recruit','🎓 WYNIK REKRUTACJI',`<@${i.user.id}> — ${e.percent}% — **${e.percent>=70?'ZDAŁ':'NIE ZDAŁ'}**`)}save();await i.update({content:'✅ Odpowiedź zapisana.',embeds:[],components:[]});return examQuestion(i.channel,i.user.id,e.q)}
if(i.isButton()&&['app-accept','app-reject'].includes(i.customId)){if(!staff(i.member))return i.reply({content:'❌ Brak uprawnień.',ephemeral:true});const a=db.applications.find(x=>x.channel===i.channel.id&&x.status==='OCZEKUJE');if(!a)return i.reply({content:'❌ Brak oczekującego podania.',ephemeral:true});a.status=i.customId==='app-accept'?'PRZYJĘTE':'ODRZUCONE';a.decidedBy=i.user.id;a.decidedAt=new Date().toISOString();save();await post(i.guild,'status','📊 STATUS REKRUTACJI',`<@${a.user}> — **${a.status}**`);return i.reply(`✅ ${a.status}`)}
if(i.isButton()&&i.customId==='close'){if(i.channel?.topic?.startsWith('ZW-TICKET:')){await i.reply('🔒 Zamykam ticket.');return setTimeout(()=>i.channel.delete().catch(()=>{}),1200)}return}
if(!i.isChatInputCommand())return;
const staffOnly=['zw-rozkaz','zw-plus','zw-minus','zw-awans','zw-degradacja','zw-wyroznienie','zw-postepowanie','zw-numer','zw-material','zw-szkolenie','zw-egzamin-szkolenie','zw-kwalifikacja','zw-archiwum'];if(staffOnly.includes(i.commandName)&&!staff(i.member))return i.reply({content:'❌ Brak uprawnień kadry.',ephemeral:true});const u=i.user,g=i.guild;
if(i.commandName==='zw-panel'){const c=find(g,'panel');if(!c)return i.reply({content:'❌ Brak panel-podania.',ephemeral:true});await c.send(panel());return i.reply({content:'✅ Panel wysłany.',ephemeral:true})}
if(i.commandName==='zw-zamknij'){if(!i.channel?.topic?.startsWith('ZW-TICKET:'))return i.reply({content:'❌ To nie ticket.',ephemeral:true});await i.reply('🔒 Zamykam.');return setTimeout(()=>i.channel.delete().catch(()=>{}),1200)}
if(i.commandName==='zw-podania')return i.reply({embeds:[new EmbedBuilder().setTitle('📋 Podania').setDescription(`Wszystkie: **${db.applications.length}**\nOczekujące: **${db.applications.filter(x=>x.status==='OCZEKUJE').length}**`)],ephemeral:true});if(i.commandName==='zw-egzaminy')return i.reply({embeds:[new EmbedBuilder().setTitle('🎓 Egzaminy').setDescription(`Rekrutacyjne: **${db.exams.length}**\nSzkoleniowe: **${db.trainingExams.length}**`)],ephemeral:true});
if(i.commandName==='zw-raport'){const t=i.options.getString('tresc');db.reports.push({user:u.id,t:t,at:new Date().toISOString()});save();await post(g,'reports','📋 RAPORT SŁUŻBOWY',`<@${u.id}>\n${t}`);return i.reply({content:'✅ Raport zapisany.',ephemeral:true})}if(i.commandName==='zw-meldunek'){const t=i.options.getString('tresc');db.meldunki.push({user:u.id,t,at:new Date().toISOString()});save();await post(g,'meldunki','📡 MELDUNEK',`<@${u.id}>\n${t}`);return i.reply({content:'✅ Meldunek zapisany.',ephemeral:true})}if(i.commandName==='zw-rozkaz'){const t=i.options.getString('tytul'),x=i.options.getString('tresc');db.orders.push({title:t,text:x,user:u.id,at:new Date().toISOString()});save();await post(g,'orders','📜 ROZKAZ — '+t,x);return i.reply({content:'✅ Rozkaz zapisany.',ephemeral:true})}
if(['zw-plus','zw-minus'].includes(i.commandName)){const t=i.options.getUser('osoba'),p=i.options.getInteger('punkty'),r=i.options.getString('powod'),d=person(t),plus=i.commandName==='zw-plus';d[plus?'plus':'minus']+=p;d.history.push({type:plus?'PLUS':'MINUS',points:p,reason:r,actor:u.id,at:new Date().toISOString()});save();await post(g,'cases',plus?'➕ PLUS':'➖ MINUS',`<@${t.id}> — ${p} pkt\n${r}`);return i.reply({content:'✅ Zapisano.',ephemeral:true})}
if(['zw-awans','zw-degradacja'].includes(i.commandName)){const t=i.options.getUser('osoba'),r=i.options.getString('stopien'),why=i.options.getString('powod'),d=person(t),old=d.rank;d.rank=r;d.history.push({type:i.commandName,from:old,to:r,reason:why,actor:u.id,at:new Date().toISOString()});save();await post(g,i.commandName==='zw-awans'?'promotions':'demotions',i.commandName==='zw-awans'?'⬆️ AWANS':'⬇️ DEGRADACJA',`<@${t.id}>\n${old} → ${r}\n${why}`);return i.reply({content:'✅ Zapisano.',ephemeral:true})}
if(['zw-wyroznienie','zw-postepowanie'].includes(i.commandName)){const t=i.options.getUser('osoba'),x=i.options.getString('opis'),d=person(t);if(i.commandName==='zw-wyroznienie')d.awards.push(x);else{d.reprimands++;db.proceedings.push({target:t.id,text:x,actor:u.id,at:new Date().toISOString()})}d.history.push({type:i.commandName,text:x,actor:u.id,at:new Date().toISOString()});save();await post(g,i.commandName==='zw-wyroznienie'?'awards':'proceedings',i.commandName==='zw-wyroznienie'?'🏅 WYRÓŻNIENIE':'⚠️ POSTĘPOWANIE',`<@${t.id}>\n${x}`);return i.reply({content:'✅ Zapisano.',ephemeral:true})}
if(['zw-karta','zw-status'].includes(i.commandName)){const t=i.options.getUser('osoba')||u,d=person(t);return i.reply({embeds:[new EmbedBuilder().setTitle('🪪 KARTA SŁUŻBOWA').setDescription(`Osoba: <@${t.id}>\nNumer: **${d.number}**\nStopień: **${d.rank}**\nPlusy: **${d.plus}**\nMinusy: **${d.minus}**\nPostępowania: **${d.reprimands}**\nSzkolenia: **${d.trainings.length}**\nKwalifikacje: **${d.qualifications.length}**`)],ephemeral:true})}if(i.commandName==='zw-kadra'){const a=Object.values(db.people).filter(x=>x.rank!=='Kandydat');return i.reply({embeds:[new EmbedBuilder().setTitle('👮 KADRA').setDescription(a.length?a.map(x=>`**${x.number}** — ${x.rank} — <@${x.id}>`).join('\n'):'Brak danych.')],ephemeral:true})}if(i.commandName==='zw-numer'){const t=i.options.getUser('osoba'),d=person(t);return i.reply({content:`✅ <@${t.id}> ma numer **${d.number}**.`,ephemeral:true})}
if(i.commandName==='zw-material'){const t=i.options.getString('tytul'),x=i.options.getString('tresc');db.materials.push({title:t,text:x,user:u.id,at:new Date().toISOString()});save();await post(g,'materials','📚 MATERIAŁ — '+t,x);return i.reply({content:'✅ Dodano.',ephemeral:true})}if(i.commandName==='zw-szkolenie'){const t=i.options.getUser('osoba'),n=i.options.getString('nazwa'),r=i.options.getString('wynik'),d=person(t);d.trainings.push({name:n,result:r,at:new Date().toISOString()});save();await post(g,'trainings','🎓 SZKOLENIE',`<@${t.id}> — ${n}\nWynik: ${r}`);return i.reply({content:'✅ Zapisano.',ephemeral:true})}if(i.commandName==='zw-egzamin-szkolenie'){const t=i.options.getUser('osoba'),n=i.options.getString('nazwa'),p=i.options.getInteger('procent');db.trainingExams.push({target:t.id,name:n,percent:p,passed:p>=70,at:new Date().toISOString()});save();await post(g,'examResults','📝 WYNIK EGZAMINU',`<@${t.id}> — ${n}\n**${p}%** — **${p>=70?'ZDAŁ':'NIE ZDAŁ'}**`);return i.reply({content:'✅ Zapisano.',ephemeral:true})}if(i.commandName==='zw-kwalifikacja'){const t=i.options.getUser('osoba'),n=i.options.getString('nazwa'),s=i.options.getString('status'),d=person(t);d.qualifications.push({name:n,status:s,at:new Date().toISOString()});save();await post(g,'qualifications','📋 KWALIFIKACJA',`<@${t.id}> — ${n}\n${s}`);return i.reply({content:'✅ Zapisano.',ephemeral:true})}
if(i.commandName==='zw-sluzba'){const d=person(u),a=i.options.getString('akcja');if(a==='start'){db.duty[u.id]=Date.now();save();return i.reply({content:'🟢 Służba rozpoczęta.',ephemeral:true})}if(!db.duty[u.id])return i.reply({content:'❌ Brak rozpoczętej służby.',ephemeral:true});const m=Math.round((Date.now()-db.duty[u.id])/60000);d.duty+=m;delete db.duty[u.id];save();return i.reply({content:`🔴 Służba zakończona: **${m} min**. Łącznie: **${d.duty} min**.`,ephemeral:true})}
if(i.commandName==='zw-archiwum'){const t=i.options.getUser('osoba'),d=person(t);return i.reply({embeds:[new EmbedBuilder().setTitle('📁 ARCHIWUM KADR').setDescription(d.history.slice(-20).map(x=>`• **${x.type}** — ${x.reason||x.text||x.name||`${x.from||''} → ${x.to||''}`}`).join('\n')||'Brak historii.')],ephemeral:true})}if(i.commandName==='zw-statystyki')return i.reply({embeds:[new EmbedBuilder().setTitle('📊 STATYSTYKI').setDescription(`Funkcjonariusze: **${Object.keys(db.people).length}**\nPodania: **${db.applications.length}**\nRaporty: **${db.reports.length}**\nMeldunki: **${db.meldunki.length}**\nRozkazy: **${db.orders.length}**\nSzkolenia: **${db.trainings.length}**\nEgzaminy: **${db.exams.length+db.trainingExams.length}**`)],ephemeral:true})
}catch(e){console.error(e);if(!i.replied&&!i.deferred)await i.reply({content:'❌ Błąd systemu ŻW.',ephemeral:true}).catch(()=>{})}});
client.login(TOKEN);